#!/bin/bash

xmodmap -e "remove control = Control_L"
#remove caps
xmodmap -e "remove lock = Caps_Lock"


xmodmap -e "keycode 37=Caps_Lock"
#change caps to control
xmodmap -e "keycode 66 = Control_R Control_R "



xmodmap -e "keycode 49 = Escape"

xmodmap -e "keycode 9 = grave"



xmodmap -e "keycode 22 = backslash bar"

xmodmap -e "keycode 51=BackSpace"

xmodmap -e "keycode 62 = F5"




xmodmap -e "add control = Control_R"
xmodmap -e "add lock = Caps_Lock"


#keyTweak in windows


#you can't put this file under /etc/init.d because xmodmap works under X windows 
#you should use "startup applications" and delay 2s to start  
#or edit /home/$your_home/.config/autostart/keymap.desktop 
#content  begin

#[Desktop Entry]
#Type=Application
#Exec=/tool/keymap
#X-GNOME-Autostart-enabled=false
#NoDisplay=false
#Hidden=false
#Name[en_US]=keymap
#Comment[en_US]=
#X-GNOME-Autostart-Delay=2

#content end

